### ISSUE TITLE
variable already declared in this scope

### ISSUE THREAD

**Issue by po-stulate** [bamboo/idris2dart#1]
First, any way I can show support to your work? Really like what this project is doing.

I was playing around with idris2dart, and tried to compile itself to dart, but failed with some variable redefined errors:
[https://gist.github.com/PoYen000227/59bd58f3b311122b6bdda4a9255b39e5](https://gist.github.com/PoYen000227/59bd58f3b311122b6bdda4a9255b39e5)

Is this a bug? Or is it planned to support self compiling?

**Comment by bamboo** [comment]
> First, any way I can show support to your work? Really like what this project is doing.

Thanks, @PoYen000227. You can [buy me a coffee](https://www.buymeacoffee.com/rodrigobamboo) if you want.

> ... failed with some variable redefined errors... Is this a bug?

That looks a lot like https://github.com/idris-lang/Idris2/issues/643.

> is it planned to support self compiling?

It is not something I'm actively pursuing but yes.

**Comment by po-stulate** [comment]
Thanks for the reply, looking forward to the updates!
btw, your payment method doesn't seem to work. :)

**Comment by bamboo** [comment]
Fixed by https://github.com/idris-lang/Idris2/pull/684. Thanks for the report!

**Comment by bamboo** [comment]
Hey @po-stulate, my [buy me a coffee](https://www.buymeacoffee.com/rodrigobamboo) account should be operational now if you'd still like to help me with testing it :)

Cheers!
