### ISSUE TITLE
Foreign function argument values of type `Bool` should be converted to Dart `bool`

### ISSUE THREAD

**Issue by rafaelprev** [bamboo/idris2dart#4]
I don't know if this is something that it is just not implemented yet or its really a bug, 

when I'm trying to use properties of flutter widgets that take a bool as parameter like obscureText from TextField widget, it compile to 0 or 1 instead of dart true or false

**Comment by bamboo** [comment]
Foreign function argument conversion from Idris `Bool` to Dart `bool` hasn't been implemented yet.

**Comment by bamboo** [comment]
Please declare the property as `DartBool` instead of `Bool` and use `true` and `false` instead of `True` and `False`.
