### ISSUE TITLE
Make all stops with Error

### ISSUE THREAD

**Issue by oco-adam** [bamboo/idris2dart#6]
Hi, 

First of all, thanks very much for creating this project - it's a great idea and potentially beautiful thing!

However, I'm having an issues running Make all - I've tried on Mac and linux Ubuntu and I'm hitting the same issue.

I went through the steps here: https://github.com/idris-lang/Idris2/blob/master/INSTALL.md#2-installing-without-an-existing-idris-2 to install a self-hosted version of Idris2, I confirmed it was working by running the tests and then I ran ```Make install-api``` in clone of the Idris2 repo dir to install the API. 

I also then followed the steps here https://github.com/idris-lang/Idris2/blob/master/INSTALL.md#2-installing-without-an-existing-idris-2 to check that I could make a new backend and it all seemed to be working.

But when I clone your project and run ```Make all``` and I get the following:

```
idris2 --build idris2dart.ipkg
1/3: Building Primitives (src/Primitives.idr)
2/3: Building Printer (src/Printer.idr)
Error: While processing right hand side of writeDocTo. While processing right hand side of writeDocTo,nSpaces. Undefined name replicate. 
Printer:131:17--131:26
 127 |   Nest w d => writeDocTo f d (nSpaces (fromInteger (cast w) + length i))
 128 |   Nil => pure ok
 129 |   where
 130 |     nSpaces : Nat -> String
 131 |     nSpaces i = replicate i ' '
                       ^^^^^^^^^
Did you mean: replace?
make: *** [Makefile:10: build/exec/idris2dart] Error 1
```

Any help with this would be much appreciated.

**Comment by bamboo** [comment]
Hi @oco-adam, thanks for the report. Fixed in d38344ef7d010d5f4715ad67cc3078eab5407f3f

**Comment by oco-adam** [comment]
Thanks for the quick response - the `make all` command now finishes. 

However, when I try and compile a file or package to dart nothing seems to happen.
e.g. if I go to /examples/flutterdoodle and execute: ```idris2dart --build flutterdoodle.ipkg```
then no files are generated.

I tried running your tests with `make test` and I get the following:

```root@ubuntu:~/idris2dart# make test
cd tests && /root/idris2dart/tests/build/exec/runtests /root/idris2dart/build/exec/idris2dart
Found dart at /snap/bin/dart
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Could not find a command named "./build/exec/args".
...
...
```
Then all of the tests fail.

**Comment by oco-adam** [comment]
The above secondary issue with `make all` not doing anything was only on linux - I just tried again on macOS and everything is working fine. So the second issue is probably just more a reflection of my lack of linux experience.

I'm closing this issue because the initial issue is fixed. Thanks again.
